version: '3.8'

services:

  app:
    build: .
    ports:
        - "8080:8080"
    container_name: drive
    depends_on:
      - mysqldb
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/drive?useSSL=false&allowPublicKeyRetrieval=true
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: root


  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drive
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - drive:/var/lib/mysql

volumes:
 drive: